name: build_and_publish_snap

on:
   push:
      branches: [main]
      paths-ignore:
         - "**/*.md"
         - "**/.gitignore"
         - "**/.gitattributes"

   pull_request:
      branches: [main]
      paths-ignore:
         - "**/*.md"
         - "**/.gitignore"
         - "**/.gitattributes"

jobs:
   build:
      runs-on: ubuntu-latest

      steps:
         - uses: actions/checkout@v3

         - name: Set up Node.js
           uses: actions/setup-node@v3
           with:
              node-version: "22"

         - name: Install dependencies
           run: npm install

         - name: Build Snap package
           env:
              ELECTRON_DISABLE_SANDBOX: 1
           run: npm run build

         - name: Upload build artifact
           uses: actions/upload-artifact@v4
           with:
              name: snap-package
              path: dist/*.snap
              if-no-files-found: error

   test:
      runs-on: ubuntu-latest
      needs: build

      steps:
         - uses: actions/checkout@v3

         - name: Set up Node.js
           uses: actions/setup-node@v3
           with:
              node-version: "22"

         - name: Install dependencies
           run: npm install

         - name: Run tests
           run: npm run ci-test

   deploy:
      runs-on: ubuntu-latest
      needs: [build, test]
      if: github.event_name == 'push'

      steps:
         - uses: actions/checkout@v3

         - name: Download Snap artifact
           uses: actions/download-artifact@v4
           with:
              name: snap-package
              path: ./dist

         - name: Install Snapcraft
           run: sudo snap install snapcraft --classic

         - name: Upload Snap package to Ubuntu Store
           env:
              SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_LOGIN_TOKEN }}
           run: |
              echo "Uploading Snap to Ubuntu Store..."
              snapcraft upload ./dist/*.snap --release stable
