name: build_and_publish_snap

on:
   push:
      branches: [main]
      paths-ignore:
         - "**/*.md"
         - "**/.gitignore"
         - "**/.gitattributes"
   pull_request:
      branches: [main]
      paths-ignore:
         - "**/*.md"
         - "**/.gitignore"
         - "**/.gitattributes"

jobs:
   build-and-publish:
      runs-on: ubuntu-latest

      steps:
         - uses: actions/checkout@v3

         - name: Set up Node.js
           uses: actions/setup-node@v3
           with:
              node-version: "22"

         - name: Install dependencies
           run: npm install

         - name: Run tests
           run: npm run ci-test

         - name: Build Snap package
           env:
              ELECTRON_DISABLE_SANDBOX: 1
           run: npm run build

         - name: Install Snapcraft
           if: github.event_name == 'push'
           run: sudo snap install snapcraft --classic

         - name: Login to Snapcraft
           if: github.event_name == 'push'
           env:
              SNAPCRAFT_LOGIN_TOKEN: ${{ secrets.SNAPCRAFT_LOGIN_TOKEN }}
           run: echo "$SNAPCRAFT_LOGIN_TOKEN" | snapcraft login --with -

         - name: Push Snap package to Ubuntu Store
           if: github.event_name == 'push'
           run: snapcraft push dist/*.snap --release stable
